application: gglasspuppy 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
  #POST
- url: /register/.*
  script: register.application
  secure: always

  #POST
- url: /scanner/.*
  script: scanner.application 
  secure: always 

  #POST
- url: /backup/.*
  script: backup.application 
  secure: always

  #POST
- url: /report/.*
  script: report.application 
  #secure: always

- url: /read/.*
  script: read.application 
  #secure: always
  
- url: /images
  static_dir : images  
  
- url: /themes
  static_dir : themes   
  
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest